language: bash

env:
  global:
    - REPO="${TRAVIS_REPO_SLUG#*/}"
    - OWNER=plus3it
    - DEPLOY_SLUG=$OWNER/$REPO
    - TF_INPUT=0

stages:
  - test
  - deploy
  - release

jobs:
  include:
    - stage: test
      env:
        - JOB="Terraform Format Verification"
      install:
        - make terraform/install
      script:
        - make terraform/lint
    - stage: test
      env:
        - JOB="JSON Lint/Format"
      install:
        - jq --version
      script:
        - make json/lint
    - stage: release
      env:
        - JOB="Deploy to GitHub Releases"
        - PRIOR_VERSION=$(git describe --abbrev=0 --tags)
        - RELEASE_VERSION=$(grep '^current_version' $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //')
        - RELEASE_BODY="* [$REPO v$RELEASE_VERSION changes](https://github.com/$OWNER/$REPO/compare/$PRIOR_VERSION...$RELEASE_VERSION)"
      script: skip
      before_deploy:
        - echo PRIOR_VERSION = $PRIOR_VERSION
        - echo RELEASE_VERSION = $RELEASE_VERSION
        - echo RELEASE_BODY = $RELEASE_BODY
      deploy:
        provider: releases
        name: $RELEASE_VERSION
        tag_name: $RELEASE_VERSION
        body: $RELEASE_BODY
        draft: false
        api_key:
          secure: DSNCRy5c3UMD3r0vLoYW95ReHeqEb31u9g9RNI/HKYQxHwAeExIcewAV46OpXsRpVKnsxRwGiF67Wy6fdB/W9OAMsOkI2HNkSXJRTAuv2VVhK+cdBHWlG2hVl5JdIMjVxUQlTCE+R+8pltQJ+MGvBQrim867yiOGX6JpNU8bAVjLSb/Byem+SCqWmGRVbXyRsVDoxcFwVqPaIjn5zJTmyPYPghp7dfRShLTnYczajUkiBvfa/YNFQ8mzfhgwu6++gu+76YPfvIBRBm/fTsqMZitVMuGD6lLwH+BpIJkmitO+JXrlt3uD9X+XF0RZ2smTE2S8glRsxlF6fWDoigDUb9rcsSyGI5cq0CC354Z06KzLaL+Qqr6V9N13Q9CVJWm11tZKWO2gGj7kshWq+leoiadxAhi4eeYnWFaO4hIbuYK9tAntmC3f3Gn0QILzjmwi0YLaYrr5v+XDM+R8ucX6eOT9GmgLX3zfaWZHC3OUe6FGyrOxdTiJ9t/GqzGqGC7saJun4WYD/DFLk5OjiWdYzHg5+djHRiIT8eZhceRkdmCuUjqWACvGdFo8EHIo64kHFlyGIoS3d85JFrB0m1DEwZUA+rdv8eS+46d7X39/NieB+WcSD2BGTfkDDOYoe6UsiC75plIT3M6aoZuKDgBtsMTfwV93lsP+IAcartzCj7w=
        on:
          branch: master
          repo: $DEPLOY_SLUG
          condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'
    - stage: deploy
      language: python
      python: "3.6"
      env:
        - JOB="Deploy to release environment"
      install: skip
      script: skip
      before_deploy:
        - echo TAG = $TRAVIS_TAG
        - echo BRANCH = $TRAVIS_BRANCH
        - pip install pipenv
        - make terraform/install terragrunt/install
      deploy:
        - provider: script
          script: TF_VAR_bucket_name="${DEV_BUCKET}" TF_VAR_s3_objects_map="${DEV_OBJECTS_MAP}" make deploy/dev
          on:
            branch: master
            repo: $DEPLOY_SLUG
          skip_cleanup: true
        - provider: script
          script: TF_VAR_bucket_name="${RELEASE_BUCKET}" TF_VAR_s3_objects_map="${RELEASE_OBJECTS_MAP}" make deploy/release
          on:
            tags: true
            repo: $DEPLOY_SLUG
          skip_cleanup: true
