version: 1

update_configs:

  - package_manager: "terraform"
    directory: "/dev/files-repo"
    update_schedule: "daily"

  - package_manager: "terraform"
    directory: "/dev/salt-repo"
    update_schedule: "daily"

  - package_manager: "terraform"
    directory: "/release/bucket-list"
    update_schedule: "daily"

  - package_manager: "terraform"
    directory: "/release/copy-bucket"
    update_schedule: "daily"

  - package_manager: "terraform"
    directory: "/release/salt-yum-defs"
    update_schedule: "daily"

  - package_manager: "docker"
    directory: "/"
    update_schedule: "daily"
