name: Update terraform dependencies

on:
  schedule:
    - cron:  '0 6 * * *'

jobs:
  dependabot-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: update terraform dependencies - /dev/files-repo
        uses: plus3it/dependabot-terraform-action@p3-implementation
        with:
          directory: /dev/files-repo
          github_dependency_token: ${{ secrets.GH_READONLY_TOKEN }}
      - name: update terraform dependencies - /dev/salt-repo
        uses: plus3it/dependabot-terraform-action@p3-implementation
        with:
          directory: /dev/salt-repo
          github_dependency_token: ${{ secrets.GH_READONLY_TOKEN }}
      - name: update terraform dependencies - /release/bucket-list
        uses: plus3it/dependabot-terraform-action@p3-implementation
        with:
          directory: /release/bucket-list
          github_dependency_token: ${{ secrets.GH_READONLY_TOKEN }}
      - name: update terraform dependencies - /release/copy-bucket
        uses: plus3it/dependabot-terraform-action@p3-implementation
        with:
          directory: /release/copy-bucket
          github_dependency_token: ${{ secrets.GH_READONLY_TOKEN }}
      - name: update terraform dependencies - /release/salt-yum-defs
        uses: plus3it/dependabot-terraform-action@p3-implementation
        with:
          directory: /release/salt-yum-defs
          github_dependency_token: ${{ secrets.GH_READONLY_TOKEN }}
